name: 'Build CMake'
description: 'Configure, Build and Test a CMake project'
author: 'Ashutosh Varma'
inputs:
  build-type:              
    description: 'CMake build type (Release, Debug, MinSizeRel, RelWithDebInfo)'
    default: 'Release'
  cc:
    description: 'C Compiler for toolchain'
    default: 'gcc'
  cxx:
    description: 'C++ Compiler for toolchain'
    default: 'g++'
  target:
    description: CMake build target
    default: all
  parallel:
    description: Number of concurrent jobs for build and test
    default: 4
  build-dir:
    description: Relative path of build directory with respect to root of repo
    default: build
  run-test:
    description: Run CTest or not
    default: false
  install-build:
    description: Run 'cmake --install' or not
    default: false
  submodule-update:
    description: Update git submodules
    default: false
  options:
    description: Misc Options to pass to CMake while configuring project
  ctest-options:
    description: Misc Options to pass to CTest
  
runs:
  using: 'node12'
  main: 'dist/index.js'
